---
title: "Task 8"
author: "Cody Jenson"
date: "2/2/2021"
output: 
  html_document:
    keep_md: yes
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '', fig.width = 12, fig.height = 4
)
```

```{r}
library(tidyverse)
library(mosaic)
library(gapminder)
```

```{r}
gap <- gapminder %>%
  filter(country != "Kuwait") %>%
  group_by(year, continent) %>%
  mutate(w_mean = weighted.mean(weighted.mean(gdpPercap, pop/100000)))

ggplot(gap) +
  geom_point(aes(x = year, 
                 y = gdpPercap, 
                 color = continent, 
                 group = country,
                 size = pop/100000)) +
  geom_line(aes(x = year, 
                y = gdpPercap,
                color = continent, 
                group = country)) +
  geom_point(aes(x = year, 
                 y = w_mean,
                 size = pop/100000)) +
  facet_grid(cols = vars(continent)) +
  scale_size(name = "Population (100k)") +
  scale_color_discrete(name = "Continent") +
  theme_bw()


```

