---
title: "Task 11"
author: "Cody Jenson"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(mosaic)
```


```{r}
dat <- read_csv("https://github.com/ktoutloud/classslides/raw/master/math335/data/M335_excess-mortality-p-scores.csv")
mort <- dat %>% 
  mutate(Spain = Spain * 100)  %>%
  pivot_longer(cols = -c(date), 
               names_to = "country", 
               values_to = "score") %>% 
  filter(country %in% c("Portugal", 
                        "Italy", 
                        "Belgium", 
                        "New Zealand")) %>%
  na.omit()

label_points <- mort %>%
  group_by(country) %>%
  filter(row_number(desc(date)) == 1)

over_100 <- mort %>%
  filter(score >= 100)

mort_us <- dat %>% 
  mutate(Spain = Spain * 100)  %>%
  pivot_longer(cols = -c(date), 
               names_to = "country", 
               values_to = "score") %>% 
  filter(country %in% c("Portugal", 
                        "Italy", 
                        "Belgium", 
                        "New Zealand",
                        "United States")) %>%
  na.omit()

label_points_us <- mort_us %>%
  group_by(country) %>%
  filter(row_number(desc(date)) == 1)

us_only <- dat %>% 
  mutate(Spain = Spain * 100)  %>%
  pivot_longer(cols = -c(date), 
               names_to = "country", 
               values_to = "score") %>% 
  filter(country == "United States") %>%
  na.omit()
```

```{r Part 1, warning=FALSE}
ggplot(mort, aes(x = date,y = score, color = country)) +
  geom_point() +
  geom_line() +
  labs(title = str_wrap("Excess mortality during COVID-19: Deaths from all causes compared to previous years, all ages"),
       subtitle = str_wrap("Shown is how the number of weekly or monthly deaths in 2020–2021 differs as a percentage from the average number of deaths in the same period over the years 2015–2019. This metric is called the P-score. The reported number of deaths might not count all deaths that occurred due to incomplete coverage and delays in death reporting."),
       caption = c("Source: Human Mortality Database (2021), UK Office for National Statistics (2020)","OurWorldData.org/coronavirus")) +
  scale_y_continuous(breaks = seq(0,140, by = 20), labels = function(x)paste0(x, "%")) +
  scale_x_date(breaks = c(as.Date("2020-01-05"), 
                           as.Date("2020-03-11"), 
                           as.Date("2020-04-30"), 
                           as.Date("2020-06-19"), 
                           as.Date("2020-08-08"), 
                           as.Date("2020-09-27"), 
                           as.Date("2020-11-16"), 
                           as.Date("2021-01-24")), 
                labels = c("Jan 5, 2020", "Mar 11",
                           "Apr 30", "Jun 19", "Aug 8",
                           "Sep 27", "Nov 16", "Jan 24, 2021")) +
   expand_limits(x = as.Date('2021-06-01')) +
   theme(panel.background = element_blank(),
         plot.background = element_blank(),
         legend.position = "none",
         panel.grid.major.y = element_line(color = "grey88", linetype = "dashed"),
         axis.title = element_blank()) +
  geom_label(aes(label = country), data = label_points)
  
  
```


```{r Part 2, warning=FALSE}
ggplot(mort, aes(x = date,y = score, color = country)) +
  geom_point() +
  geom_line() +
  labs(title = str_wrap("Excess mortality during COVID-19: Deaths from all causes compared to previous years, all ages"),
       subtitle = str_wrap("Shown is how the number of weekly or monthly deaths in 2020–2021 differs as a percentage from the average number of deaths in the same period over the years 2015–2019. This metric is called the P-score. The reported number of deaths might not count all deaths that occurred due to incomplete coverage and delays in death reporting."),
       caption = c("Source: Human Mortality Database (2021), UK Office for National Statistics (2020)","OurWorldData.org/coronavirus")) +
  scale_y_continuous(breaks = seq(0,140, by = 20), labels = function(x)paste0(x, "%")) +
  scale_x_date(breaks = c(as.Date("2020-01-05"), 
                           as.Date("2020-03-11"), 
                           as.Date("2020-04-30"), 
                           as.Date("2020-06-19"), 
                           as.Date("2020-08-08"), 
                           as.Date("2020-09-27"), 
                           as.Date("2020-11-16"), 
                           as.Date("2021-01-24")), 
                labels = c("Jan 5, 2020", "Mar 11",
                           "Apr 30", "Jun 19", "Aug 8",
                           "Sep 27", "Nov 16", "Jan 24, 2021")) +
   expand_limits(x = as.Date('2021-06-01')) +
   theme(panel.background = element_blank(),
         plot.background = element_blank(),
         legend.position = "none",
         panel.grid.major.y = element_line(color = "grey88", linetype = "dashed"),
         axis.title = element_blank()) +
  geom_label(aes(label = country), data = label_points) +
  geom_label(aes(label = score), data = over_100, nudge_x = 30)
```
First way to draw attention to points over 100: Label them with geom_label.

```{r}
ggplot(mort, aes(x = date,y = score, color = country)) +
  geom_point() +
  geom_line() +
  labs(title = str_wrap("Excess mortality during COVID-19: Deaths from all causes compared to previous years, all ages"),
       subtitle = str_wrap("Shown is how the number of weekly or monthly deaths in 2020–2021 differs as a percentage from the average number of deaths in the same period over the years 2015–2019. This metric is called the P-score. The reported number of deaths might not count all deaths that occurred due to incomplete coverage and delays in death reporting."),
       caption = c("Source: Human Mortality Database (2021), UK Office for National Statistics (2020)","OurWorldData.org/coronavirus")) +
  scale_y_continuous(breaks = seq(0,140, by = 20), labels = function(x)paste0(x, "%")) +
  scale_x_date(breaks = c(as.Date("2020-01-05"), 
                           as.Date("2020-03-11"), 
                           as.Date("2020-04-30"), 
                           as.Date("2020-06-19"), 
                           as.Date("2020-08-08"), 
                           as.Date("2020-09-27"), 
                           as.Date("2020-11-16"), 
                           as.Date("2021-01-24")), 
                labels = c("Jan 5, 2020", "Mar 11",
                           "Apr 30", "Jun 19", "Aug 8",
                           "Sep 27", "Nov 16", "Jan 24, 2021")) +
   expand_limits(x = as.Date('2021-06-01')) +
   theme(panel.background = element_blank(),
         plot.background = element_blank(),
         legend.position = "none",
         panel.grid.major.y = element_line(color = "grey88", linetype = "dashed"),
         axis.title = element_blank()) +
  geom_label(aes(label = country), data = label_points) +
  geom_point(data = over_100, size = 3, shape = 1)
```

Method #2: Draw a circle around the points over 100


```{r}
ggplot(mort, aes(x = date,y = score, color = country)) +
  geom_point() +
  geom_line() +
  labs(title = str_wrap("Excess mortality during COVID-19: Deaths from all causes compared to previous years, all ages"),
       subtitle = str_wrap("Shown is how the number of weekly or monthly deaths in 2020–2021 differs as a percentage from the average number of deaths in the same period over the years 2015–2019. This metric is called the P-score. The reported number of deaths might not count all deaths that occurred due to incomplete coverage and delays in death reporting."),
       caption = c("Source: Human Mortality Database (2021), UK Office for National Statistics (2020)","OurWorldData.org/coronavirus")) +
  scale_y_continuous(breaks = seq(0,140, by = 20), labels = function(x)paste0(x, "%")) +
  scale_x_date(breaks = c(as.Date("2020-01-05"), 
                           as.Date("2020-03-11"), 
                           as.Date("2020-04-30"), 
                           as.Date("2020-06-19"), 
                           as.Date("2020-08-08"), 
                           as.Date("2020-09-27"), 
                           as.Date("2020-11-16"), 
                           as.Date("2021-01-24")), 
                labels = c("Jan 5, 2020", "Mar 11",
                           "Apr 30", "Jun 19", "Aug 8",
                           "Sep 27", "Nov 16", "Jan 24, 2021")) +
   expand_limits(x = as.Date('2021-06-01')) +
   theme(panel.background = element_blank(),
         plot.background = element_blank(),
         legend.position = "none",
         panel.grid.major.y = element_line(color = "grey88", linetype = "dashed"),
         axis.title = element_blank()) +
  geom_label(aes(label = country), data = label_points) +
  geom_point(data = over_100, size = 3, shape = 17)
```

Method 3 change the shape entirely

```{r Part 3, warning=FALSE}
ggplot(mort_us, aes(x = date,y = score, color = country)) +
  geom_point() +
  geom_line() +
  labs(title = str_wrap("Excess mortality during COVID-19: Deaths from all causes compared to previous years, all ages"),
       subtitle = str_wrap("Shown is how the number of weekly or monthly deaths in 2020–2021 differs as a percentage from the average number of deaths in the same period over the years 2015–2019. This metric is called the P-score. The reported number of deaths might not count all deaths that occurred due to incomplete coverage and delays in death reporting."),
       caption = c("Source: Human Mortality Database (2021), UK Office for National Statistics (2020)","OurWorldData.org/coronavirus")) +
  scale_y_continuous(breaks = seq(0,140, by = 20), labels = function(x)paste0(x, "%")) +
  scale_x_date(breaks = c(as.Date("2020-01-05"), 
                           as.Date("2020-03-11"), 
                           as.Date("2020-04-30"), 
                           as.Date("2020-06-19"), 
                           as.Date("2020-08-08"), 
                           as.Date("2020-09-27"), 
                           as.Date("2020-11-16"), 
                           as.Date("2021-01-24")), 
                labels = c("Jan 5, 2020", "Mar 11",
                           "Apr 30", "Jun 19", "Aug 8",
                           "Sep 27", "Nov 16", "Jan 24, 2021")) +
   expand_limits(x = as.Date('2021-06-01')) +
   theme(panel.background = element_blank(),
         plot.background = element_blank(),
         legend.position = "none",
         panel.grid.major.y = element_line(color = "grey88", linetype = "dashed"),
         axis.title = element_blank()) +
  ggrepel::geom_label_repel(aes(label = country), data = label_points_us) +
  geom_line(data = us_only, size = 1.5)
```

To draw attention to the united states you could bold that line.

```{r Part 3, warning=FALSE}
ggplot(mort_us, aes(x = date,y = score, color = country)) +
  geom_point() +
  geom_line() +
  labs(title = str_wrap("Excess mortality during COVID-19: Deaths from all causes compared to previous years, all ages"),
       subtitle = str_wrap("Shown is how the number of weekly or monthly deaths in 2020–2021 differs as a percentage from the average number of deaths in the same period over the years 2015–2019. This metric is called the P-score. The reported number of deaths might not count all deaths that occurred due to incomplete coverage and delays in death reporting."),
       caption = c("Source: Human Mortality Database (2021), UK Office for National Statistics (2020)","OurWorldData.org/coronavirus")) +
  scale_y_continuous(breaks = seq(0,140, by = 20), labels = function(x)paste0(x, "%")) +
  scale_x_date(breaks = c(as.Date("2020-01-05"), 
                           as.Date("2020-03-11"), 
                           as.Date("2020-04-30"), 
                           as.Date("2020-06-19"), 
                           as.Date("2020-08-08"), 
                           as.Date("2020-09-27"), 
                           as.Date("2020-11-16"), 
                           as.Date("2021-01-24")), 
                labels = c("Jan 5, 2020", "Mar 11",
                           "Apr 30", "Jun 19", "Aug 8",
                           "Sep 27", "Nov 16", "Jan 24, 2021")) +
   expand_limits(x = as.Date('2021-06-01')) +
   theme(panel.background = element_blank(),
         plot.background = element_blank(),
         legend.position = "none",
         panel.grid.major.y = element_line(color = "grey88", linetype = "dashed"),
         axis.title = element_blank()) +
  ggrepel::geom_label_repel(aes(label = country), data = label_points_us) +
  geom_point(data = us_only, size = 3)
```


Or you could do the same with the points